version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cowboy-supper-backend
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=toBeModified1,toBeModified2,toBeModified3,toBeModified4
      - API_TOKEN_SALT=tobemodified
      - ADMIN_JWT_SECRET=tobemodified
      - TRANSFER_TOKEN_SALT=tobemodified
      - JWT_SECRET=tobemodified
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
      - strapi-data:/app/.tmp
    networks:
      - cowboy-supper-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cowboy-supper-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_STRAPI_URL=http://localhost:1337
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend
    depends_on:
      - backend
    networks:
      - cowboy-supper-network

volumes:
  strapi-data:

networks:
  cowboy-supper-network:
    driver: bridge
